export { default as Logo } from './Logo'
export { default as CoinSystems } from './CoinSystems'
export { default as Background } from './BackGround'
export { default as Facebook } from './Facebook'
export { default as LinkerIn } from './LinkerIn'
